### ISSUE TITLE
JS error on page load

### ISSUE THREAD

**Issue by valderman** [faldez/tanoshi#118]
When building tanoshi 0.13.0 on Debian, using rustc 1.46, wasm-pack 0.9.1 and wasm-bindgen 0.2.68, the tanoshi web UI doesn't load. Instead, the following error is thrown:

```
Uncaught (in promise) TypeError: o.run is not a function
    <anonymous> http://localhost:8080/tanoshi-web.js:1
    promise callback* http://localhost:8080/tanoshi-web.js:1
    e http://localhost:8080/tanoshi-web.js:1
    <anonymous> http://localhost:8080/tanoshi-web.js:1
    <anonymous> http://localhost:8080/tanoshi-web.js:1

Service worker event waitUntil() was passed a promise that rejected with 'NS_ERROR_INVALID_CONTENT_ENCODING: '.
```

Both debug and release builds are affected.

The official 0.13.0 Linux binary works fine, so I suspect I have a different version of some build tool than the official binary. It would be good to add known good versions for rustc, wasm-pack, wasm-bindgen, and possibly other relevant build tools to the build guide.

**Comment by faldez** [comment]
most of the time, clear the cache solve the issue. but it's a good idea, I'll try to fix version I use to build

**Comment by valderman** [comment]
Clearing the cache doesn't solve the problem unfortunately. I dug a bit deeper, and here's what I've discovered so far:

* The file `1.tanoshi-web.js` is just a stub after building `tanoshi-web`:
    ```javascript
    (window.webpackJsonp=window.webpackJsonp||[]).push([[1],{5:function(n,w){}}]);
    ```
* `tanoshi-web.wasm` doesn't get generated *at all*.
* `tanoshi-web.js` seems to get generated just fine, though it's hard to tell with minified JS.
* Using wasm-pack 0.8.0 and wasm-bindgen 0.2.40 did not affect the problem at all.
* Using an older rustc just produces compilation errors about experimental features.
* Replacing the `(1.)?tanoshi-web.[js|wasm]` files generated by the build process with the versions extracted from the official 0.13.0 binary solves the problem, so it seems that the problem is entirely on the `tanoshi-web` side.

I could live with just using the official binaries, but (1) that would prevent me from contributing and (2) I plan to run tanoshi on a Raspberry Pi 4B and there are no arm64 binaries.

**Comment by faldez** [comment]
I tried to reproduce this, using debian in a VM, but it works as expected. Can you write down the step you build, so I can reproduce the every step?

**Comment by valderman** [comment]
This is the Dockerfile I'm using. Repeating the same steps on my host machine yields the same result: a binary with a stub `1.tanoshi-web.js` and no `tanoshi-web.wasm`.
```Dockerfile
FROM debian:unstable-20200908-slim AS build

RUN apt-get update && apt-get -y install git rustc yarnpkg libssl-dev pkg-config && apt-get clean
RUN cargo install wasm-bindgen-cli wasm-pack

ENV TANOSHI_VERSION=0.13.0
WORKDIR /build
RUN git clone https://github.com/faldez/tanoshi.git && \
    git clone https://github.com/faldez/tanoshi-extensions.git && \
    cd tanoshi && git checkout v${TANOSHI_VERSION}

WORKDIR /build/tanoshi/tanoshi-web
RUN export PATH=${PATH}:/root/.cargo/bin && \
    yarnpkg install && \
    yarnpkg build

WORKDIR /build/tanoshi
RUN cargo build --release

WORKDIR /build/tanoshi-extensions
RUN cargo build --release

FROM debian:unstable-20200908-slim
EXPOSE 8080
VOLUME /data

RUN useradd -mUrd /tanoshi tanoshi && \
    chown tanoshi:tanoshi /data

USER tanoshi:tanoshi
WORKDIR /tanoshi
COPY --chown=tanoshi:tanoshi --from=build /build/tanoshi/target/release/tanoshi ./
RUN ./tanoshi ; \
    cat .tanoshi/config.yml \
        | sed -e 's/^port: .*$/port: 8080/g' \
        | sed -e 's/^plugin_path: .*$/plugin_path: \/tanoshi\/plugins/g' \
        > config.yml && \
    mv .tanoshi/plugins plugins && \
    rm -r .tanoshi && \
    ln -s /data .tanoshi
COPY --chown=tanoshi:tanoshi --from=build /build/tanoshi-extensions/target/release/*.so plugins/

USER root
CMD chown -R tanoshi:tanoshi /data && \
    setpriv --reuid=tanoshi --regid=tanoshi --init-groups \
    /tanoshi/tanoshi --config /tanoshi/config.yml
```

**Comment by faldez** [comment]
I think this is the problem
`[INFO]: Checking for the Wasm target...
Error: wasm32-unknown-unknown target not found in sysroot: "/usr"

Used rustc from the following path: "/usr/bin/rustc"
It looks like Rustup is not being used. For non-Rustup setups, the wasm32-unknown-unknown target needs to be installed manually. See https://rustwasm.github.io/wasm-pack/book/prerequisites/non-rustup-setups.html on how to do this.`

it fails to build the web app because installing rustc from apt doesn't include rustup.  I modify your Dockerfile a bit, and this works
`FROM debian:unstable-20200908-slim AS build
  
RUN apt-get update && apt-get -y install git curl build-essential yarnpkg libssl-dev pkg-config && apt-get clean

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo install wasm-bindgen-cli wasm-pack

ENV TANOSHI_VERSION=0.13.0
WORKDIR /build
RUN git clone https://github.com/faldez/tanoshi.git && \
    git clone https://github.com/faldez/tanoshi-extensions.git && \
    cd tanoshi && git checkout v${TANOSHI_VERSION}

WORKDIR /build/tanoshi/tanoshi-web
RUN yarnpkg install && \
    yarnpkg build

WORKDIR /build/tanoshi
RUN cargo build --release

WORKDIR /build/tanoshi-extensions
RUN cargo build --release

FROM debian:unstable-20200908-slim
EXPOSE 8080
VOLUME /data

RUN useradd -mUrd /tanoshi tanoshi && \
    chown tanoshi:tanoshi /data

USER tanoshi:tanoshi
WORKDIR /tanoshi
COPY --chown=tanoshi:tanoshi --from=build /build/tanoshi/target/release/tanoshi ./
RUN ./tanoshi ; \
    cat .tanoshi/config.yml \
        | sed -e 's/^port: .*$/port: 8080/g' \
        | sed -e 's/^plugin_path: .*$/plugin_path: \/tanoshi\/plugins/g' \
        > config.yml && \
    mv .tanoshi/plugins plugins && \
    rm -r .tanoshi && \
    ln -s /data .tanoshi
COPY --chown=tanoshi:tanoshi --from=build /build/tanoshi-extensions/target/release/*.so plugins/

USER root
CMD chown -R tanoshi:tanoshi /data && \
    setpriv --reuid=tanoshi --regid=tanoshi --init-groups \
    /tanoshi/tanoshi --config /tanoshi/config.yml
`
